import type { CSSProperties } from 'react'

export const legalStyles = {
  page: {
    padding: '32px 40px 48px',
    maxWidth: 1100,
    margin: '0 auto',
  } satisfies CSSProperties,
  label: {
    display: 'block',
    fontFamily: 'var(--font-mono)',
    fontSize: 10,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
    color: 'var(--muted)',
    marginBottom: 6,
  } satisfies CSSProperties,
  input: {
    width: '100%',
    padding: '10px 12px',
    background: 'var(--surface)',
    border: '1px solid var(--line)',
    color: 'var(--ink)',
    fontFamily: 'var(--font-body)',
    fontSize: 14,
    boxSizing: 'border-box' as const,
  } satisfies CSSProperties,
  textarea: {
    width: '100%',
    padding: '10px 12px',
    background: 'var(--surface)',
    border: '1px solid var(--line)',
    color: 'var(--ink)',
    fontFamily: 'var(--font-body)',
    fontSize: 14,
    resize: 'vertical' as const,
    boxSizing: 'border-box' as const,
  } satisfies CSSProperties,
  btnPrimary: {
    padding: '12px 24px',
    background: 'var(--accent)',
    border: 'none',
    color: '#141414',
    fontFamily: 'var(--font-mono)',
    fontSize: 11,
    textTransform: 'uppercase' as const,
    fontWeight: 600,
    cursor: 'pointer',
    letterSpacing: '0.08em',
  } satisfies CSSProperties,
  btnSecondary: {
    padding: '10px 18px',
    background: 'transparent',
    border: '1px solid var(--accent)',
    color: 'var(--accent)',
    fontFamily: 'var(--font-mono)',
    fontSize: 10,
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
  } satisfies CSSProperties,
  card: {
    background: 'var(--surface)',
    border: '1px solid var(--line)',
    padding: 24,
    marginBottom: 20,
  } satisfies CSSProperties,
  h1: {
    fontFamily: 'var(--font-display)',
    fontSize: 28,
    fontWeight: 400,
    marginBottom: 8,
  } satisfies CSSProperties,
}
