import type { CSSProperties } from 'react'

export const docStyles = {
  page: {
    padding: '32px 40px 48px',
    maxWidth: 1100,
    margin: '0 auto',
    minHeight: '100%',
  } satisfies CSSProperties,
  h1: {
    fontFamily: 'var(--font-display)',
    fontSize: 32,
    fontWeight: 400,
    color: '#f5f5f5',
    marginBottom: 8,
  } satisfies CSSProperties,
  subtitle: {
    fontFamily: 'var(--font-body)',
    fontSize: 14,
    color: 'rgba(245,245,245,0.55)',
    marginBottom: 32,
  } satisfies CSSProperties,
  card: {
    background: '#0a0a0a',
    border: '1px solid rgba(201, 168, 76, 0.15)',
    padding: 24,
    marginBottom: 16,
    transition: 'border-color 0.15s',
  } satisfies CSSProperties,
  cardHover: {
    borderColor: 'rgba(201, 168, 76, 0.3)',
  } satisfies CSSProperties,
  label: {
    display: 'block',
    fontFamily: 'var(--font-mono)',
    fontSize: 10,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
    color: 'rgba(201, 168, 76, 0.75)',
    marginBottom: 6,
  } satisfies CSSProperties,
  input: {
    width: '100%',
    padding: '10px 12px',
    background: '#0a0a0a',
    border: '1px solid rgba(201, 168, 76, 0.15)',
    color: '#f5f5f5',
    fontFamily: 'var(--font-body)',
    fontSize: 14,
    boxSizing: 'border-box' as const,
    borderRadius: 0,
  } satisfies CSSProperties,
  btnPrimary: {
    padding: '12px 24px',
    background: '#c9a84c',
    border: 'none',
    color: '#0a0a0a',
    fontFamily: 'var(--font-mono)',
    fontSize: 11,
    textTransform: 'uppercase' as const,
    fontWeight: 600,
    cursor: 'pointer',
    letterSpacing: '0.08em',
    borderRadius: 0,
  } satisfies CSSProperties,
  btnSecondary: {
    padding: '10px 18px',
    background: 'transparent',
    border: '1px solid rgba(201, 168, 76, 0.3)',
    color: '#c9a84c',
    fontFamily: 'var(--font-mono)',
    fontSize: 10,
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    borderRadius: 0,
  } satisfies CSSProperties,
  link: {
    color: '#c9a84c',
    textDecoration: 'none',
    fontFamily: 'var(--font-mono)',
    fontSize: 11,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  } satisfies CSSProperties,
}
